version: "3"

services:
  manager-ui:
    build: 
      context: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
    links:
      - sass-assistant
    environment:
      - REACT_APP_AUTH_URL=https://master-auth-api.external.staging.jumo.world
      - REACT_APP_UI_URL=http://0.0.0.0:8080
      - REACT_APP_API_URL=http://localhost:5000

  sass-assistant:
    build:
      context: .
      dockerfile: SassAssistantDockerfile
    volumes:
      - ./:/usr/src/app